### ISSUE TITLE
Visulization problem

### ISSUE THREAD

**Issue by GoingMyWay** [TonghanWang/ROMA#10]
Hi, again, Bro, in your paper, how did you label the numbers in PySC2? I found PySC2 has no such APIs (if I am wrong, please correct me).

![image](https://user-images.githubusercontent.com/9346460/89531653-27b74a80-d823-11ea-8824-0e4df292826c.png)

Thank you very much.

**Comment by TonghanWang** [comment]
Hi, actually, PySC2 does not has this API. We label these numbers using PPT -- We collect the coordinates and indices of all agents from the SC2 engine, and label them by hand :)

**Comment by GoingMyWay** [comment]
> Hi, actually, PySC2 does not has this API. We label these numbers using PPT -- We collect the coordinates and indices of all agents from the SC2 engine, and label them by hand :)

Thank you for your generous sharing.

**Comment by TonghanWang** [comment]
You are welcome.
