### ISSUE TITLE
The Code of trajectory encoder

### ISSUE THREAD

**Issue by GoingMyWay** [TonghanWang/ROMA#11]
Hi, again, Bro. Today I read your awesome code, in page 3 of your paper, you introduced an encoder by using GRU. However, I found there seems no trajectory encoder defined in [latent_ce_dis_rnn_agent.py](https://github.com/TonghanWang/ROMA/blob/master/src/modules/agents/latent_ce_dis_rnn_agent.py) (maybe I did not find it, correct me if I am wrong),  there is a GRU which is originally used in PyMARL for learning history observations, I think it is not the trajectory encoder. 

My another question is in equation (2), you use \tau^{t-1}_i as the input of the equation (2),

![image](https://user-images.githubusercontent.com/9346460/90535570-a27e4f00-e1ad-11ea-9e79-4927f91e912f.png)

and in the code, it seems it receives one time-step batch, which made me feel confused. Could you point out where you use it?

Maybe I have not fully understood your paper and idea. Hope you can help!

**Comment by TonghanWang** [comment]
Hi bro, sorry for the late reply. 

### Q1: About trajectory encoder.
A1: For the trajectory encoder, we reuse the one declared in `latent_ce_dis_rnn_agent.py` (also the one originally used in PyMARL). We can use a separate network, but sharing this encoder can reduce the number of parameters in our model. :) 

### Q2: \tau^{t-1}_i in Eq. 2.
A2: For \tau^{t-1}_i in Eq. 2, we also use the trajectory encoder (the one mentioned in A1) to preprocess them before calculating L_I as in Eq. 3. Trajectories have various lengths, and using the trajectory encoder allows the input of q_\xi to have a fixed length.

**Comment by GoingMyWay** [comment]
> Hi bro, sorry for the late reply.
> 
> ### Q1: About trajectory encoder.
> A1: For the trajectory encoder, we reuse the one declared in `latent_ce_dis_rnn_agent.py` (also the one originally used in PyMARL). We can use a separate network, but sharing this encoder can reduce the number of parameters in our model. :)
> 
> ### Q2: \tau^{t-1}_i in Eq. 2.
> A2: For \tau^{t-1}_i in Eq. 2, we also use the trajectory encoder (the one mentioned in A1) to preprocess them before calculating L_I as in Eq. 3. Trajectories have various lengths, and using the trajectory encoder allows the input of q_\xi to have a fixed length.

Thanks, I got it. For Q2, you used the GRU cell and input observations of each step to avoid the varying trajectories problems. That is very good trick.
