### ISSUE TITLE
Will you share the customised environments in your paper?

### ISSUE THREAD

**Issue by GoingMyWay** [TonghanWang/ROMA#12]
Hi, Bro. I found in your paper, you used many customised environments designed by you, including `6s4z_vs_10b30z`, `6z4b`, and `10z5b_vs_2z3s`. Will you release them in this repo?

**Comment by TonghanWang** [comment]
Hi, you can find it at `/src/envs/starcraft2/maps/designed/` in this repo. :)

bane_vs_bane1 is `6z4b`
`sz_vs_zb` is `6s4z_vs_10b30z`
`zb_vs_sz` is `10z5b_vs_2z3s`

**Comment by GoingMyWay** [comment]
> Hi, you can find them at `/src/envs/starcraft2/maps/designed/` in this repo. :)
> 
> `bane_vs_bane1` is `6z4b`
> `sz_vs_zb` is `6s4z_vs_10b30z`
> `zb_vs_sz` is `10z5b_vs_2z3s`

That is very nice. I found these files but I was confused and thought those were different scenarios.
