### ISSUE TITLE
Where does the number 13.9 in Dis Loss come from?

### ISSUE THREAD

**Issue by AdagioZbc** [TonghanWang/ROMA#7]
We are curious about the number 13.9 in the computation of the Dis Loss. Could you please tell us what does it mean?

--------------------------------------------
In latent_ce_dis_rnn_agent.py:

mi = th.clamp(gaussian_embed.log_prob(latent_move.view(self.bs * self.n_agents, -1))+13.9, min=-13.9).sum(dim=1,keepdim=True) / self.latent_dim

**Comment by TonghanWang** [comment]
Hi,

-13.9 ≈ log(1e-6)

Since the output of the log_prob function can be arbitrarily small, we add this number to guarantee numeric stability.

**Comment by AdagioZbc** [comment]
Thanks a lot! Your reply has solved our issue.

**Comment by TonghanWang** [comment]
Happy to see it solved. If you have any other questions, please feel free to contact us.
