### ISSUE TITLE
环境

### ISSUE THREAD

**Issue by simsimiSION** [TonghanWang/ROMA#8]
您遇到过当运行8m的时候是正常的，但是当运行25m时，程序显示以杀死的问题吗

**Comment by TonghanWang** [comment]
您好，请问您可否提供更多的运行（报错）信息，以便我们能帮到您？

**Comment by simsimiSION** [comment]
就是这样的，中间是我显示的一些环境的信息(这个在我运行8m,8m_vs_9m等环境是可以的，应该不是这个问题)，这个就直接显示 已杀死，不显示问题在哪里。。。。

[DEBUG 23:36:33] tensorflow Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
parallel
 - - - environment information - - -
{'state_shape': 1170, 'obs_shape': 285, 'n_actions': 36, 'n_agents': 27, 'episode_limit': 180}
move feats: 4
enemy feats: (30, 5)
ally feats: (26, 5)
own feats: 1
已杀死

**Comment by TonghanWang** [comment]
您跑的是27m_vs_30m吗？请问您使用的机器的内存大小和显卡参数是？

**Comment by simsimiSION** [comment]
恩是，机器是i7-9700k，32G内存，显卡是2080ti

**Comment by TonghanWang** [comment]
那可能是内存不太够的原因。主要是replay buffer开在内存上，25m或者27m_vs_30m需要30G左右的内存。您可以试试把buffer size从5000减到3000（但可能会牺牲一点performance）

**Comment by simsimiSION** [comment]
是这样呀，知道啦，谢谢您啦

**Comment by TonghanWang** [comment]
客气啦
